# Generated by Django 4.2.3 on 2023-07-30 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clients_name', models.CharField(max_length=100)),
                ('complains', models.TextField(null=True)),
                ('payments', models.FloatField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('log_by', models.CharField(max_length=50)),
                ('answer_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8)),
                ('phone_number', models.CharField(max_length=15)),
                ('logged_at', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 12, 53, 35, 7806))),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('username', models.CharField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_changed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_payments', models.FloatField(null=True)),
                ('amount_paid', models.FloatField(null=True)),
                ('pending_amount', models.FloatField(null=True)),
                ('jobs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.jobsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LogHistoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_by', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.jobsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.jobsmodel')),
            ],
        ),
    ]
