# Generated by Django 4.2.3 on 2023-07-27 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clients_name', models.CharField(max_length=100)),
                ('complains', models.TextField(null=True)),
                ('payments', models.FloatField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('log_by', models.CharField(max_length=50)),
                ('answer_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
