# Generated by Django 4.2.3 on 2023-07-30 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='amount_paid',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 20, 32, 38, 995591)),
        ),
    ]
