# Generated by Django 4.2.3 on 2023-07-31 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_jobhistory_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 9, 34, 25, 960855)),
        ),
    ]
