# Generated by Django 4.2.3 on 2023-07-31 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_jobsmodel_logged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 23, 38, 22, 457808)),
        ),
    ]
